services:
  - name: php
    type: web
    buildCommand: ""
    dockerfilePath: ./Dockerfile
    runtime: docker
    env:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: budget
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB_HOST: db
    
  - name: db
    type: web
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: budget
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB_HOST: localhost
    startCommand: ""
    ports:
      - "3307:3306"
    volumes:
      - "/docker-entrypoint-initdb.d/budget.sql:/budget.sql"
